# Site
title:              Chieh Hubert Lin
bio:                'Learn, learn, learn.'
description:        "Hubert receives his bachelor in 2018 and now working with Prof. Min Sun as a research assistance. Hubert's research interest is mainly generative models and neural architecture search. He believes that the generative model is a very important way to visualize and empirical proof that the machine intelligence can fully understand the data and the implicit meanings behind the scene. In the meanwhile, neural architecture search is the key-stone to fully-automated model design, which will be the next break-through in deep learning. What will happen after machines can iteratively self-optimize with a given dataset? Hubert hopes he can become a CLO (Chief Labelling Officer) or CPO (Chief Preprocessing Officer) after that. <br>Hubert is also looking for a PhD position in 2020."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://hubert0527.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   HuberLin

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
facebook:           chieh.hubert.lin
github-url:         hubert0527
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           杰-林-910107115
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
